// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  /**
   *  Health-check command: confirms the frontend <-> Rust IPC wiring and that the
   *  pooled DB connection (registered in `AppState`) is reachable.
   */
  ping: () => __TAURI_INVOKE<PingResponse>("ping"),
  /**
   *  Round-trips `GET /health` to the Go sidecar via the base URL the sidecar
   *  supervisor (`src/sidecar/manager.rs`) recorded on `AppState` after reading
   *  the process's startup port handshake.
   */
  sidecarHealth: () =>
    typedError<SidecarHealthResponse, string>(__TAURI_INVOKE("sidecar_health")),
};

/* Types */
export type PingResponse = {
  message: string;
  db_ok: boolean;
};

export type SidecarHealthResponse = {
  status: string;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}
