// AUTO-GENERATED by tauri-specta — do not edit by hand.
// Regenerate with `bun run gen:bindings` (or `/gen-bindings`) after changing
// any #[tauri::command] signature in apps/desktop/src-tauri.
//
// Placeholder until Phase 9 wires up the real codegen — intentionally empty.
export {};
